machine:
  environment:
    COVERALLS_REPO_TOKEN: ljISIb1TZjUpmEa33fakQdm2c66PevpVW
    COVERALLS_PARALLEL: true

notify:
  webhooks:
    - url: https://coveralls.io/webhook?repo_token=ljISIb1TZjUpmEa33fakQdm2c66PevpVW
